spring.application.name=wildeats-backend

spring.datasource.url=jdbc:mysql://localhost:3306/wildeats_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=admin123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
jwt.expiration=86400000

cors.allowed.origins=http://localhost:3000,http://localhost:5173

server.port=8081